spring.application.name=docgen
server.port=8080

# Datasource and Hikari configuration
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.hikari.max-lifetime=600000 		# Set lower DB/FireWall timeout (e.g., 10 minutes)
spring.hikari.keepalive-time=60000		# Periodically ping connections to keep them active (e.g., 1 minute)
spring.hikari.connection-timeout=30000	# Time to wait for a new connection (e.g., 30 seconds)

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true